# Generated by Django 4.1.1 on 2022-09-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_title', models.CharField(default='', max_length=140)),
                ('publisher', models.CharField(max_length=15)),
                ('private', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=140, null=True)),
                ('view', models.IntegerField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.bookcategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
