# Generated by Django 4.1.1 on 2022-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_title', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=140)),
                ('category', models.CharField(choices=[('dev', 'Development'), ('design', 'Design'), ('PM', 'project manage'), ('Culture', 'culture')], max_length=20)),
                ('tags', models.CharField(max_length=120)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
